name: Compile with SourceMod

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sm_version: ['1.8', '1.9', '1.10', '1.11']

    steps:
      - uses: actions/checkout@v1

      - name: Setup Environment
        run: |
          SOURCEMOD_PATH=$GITHUB_WORKSPACE/addons/sourcemod
          echo "SOURCEMOD_PATH=$SOURCEMOD_PATH" >> $GITHUB_ENV
          echo "SCRIPTS_PATH=$SOURCEMOD_PATH/scripting" >> $GITHUB_ENV
          echo "TESTSUITE_SCRIPTS_PATH=$GITHUB_WORKSPACE/dependencies/sm-testsuite/addons/sourcemod/scripting" >> $GITHUB_ENV

      - name: Setup SourcePawn Compiler
        uses: rumblefrog/setup-sp@master
        with:
          version: ${{ matrix.sm_version }}

      - name: Prepare Submodules (sm-testsuite)
        run: git submodule update --init

      - name: Compile Plugin
        run: spcomp $SCRIPTS_PATH/json_test.sp -i$SCRIPTS_PATH/include -i$TESTSUITE_SCRIPTS_PATH/include -O2 -t4 -v2 -w234

      - name: Upload Compiled Plugin
        uses: actions/upload-artifact@v2
        with:
          name: json_test_sm${{ matrix.sm_version }}
          path: json_test.smx
